#!/usr/bin/env python3
"""Generate the travel application CJK font subsets (D1b, reproducible).

- Source canopy: string literals in main/passport/passport_text.h plus the
  companion fixture pack content (passport_server.fixture), so UI text,
  downloaded fixture text and the font inventory cannot drift apart.
- Font source: Noto Sans CJK SC (OFL 1.1); the local copy path comes from
  PASSPORT_FONT_SOURCE and the reference + license record lives in
  assets/fonts/README.md.
- Converter: lv_font_conv 1.5.3 (pinned). Sizes 16/20, bpp 4, uncompressed,
  LVGL format.
- Negative control: U+2A302 and U+3FFFF must NOT be in the canopy or the
  font; the generation aborts if either code point ever appears.
- Output: assets/fonts/travel_font_16.c, travel_font_20.c and
  travel_glyph_inventory.json (consumed by host tests and the device-side
  pack glyph check).
"""
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEXT_H = ROOT / "main/passport/passport_text.h"
OUT_DIR = ROOT / "assets/fonts"
NEGATIVE = {0x2A302, 0x3FFFF}
ASCII_RANGE = (0x20, 0x7E)
SIZES = {16, 20}
CONVERTER_VERSION = "1.5.3"
LV_FONT_CONV = "lv_font_conv"


def extract_codepoints(header_text: str) -> set[int]:
    """Collect code points from all string-literal byte-escape sequences."""
    points: set[int] = set()
    for _name, value in re.findall(
            r'#define\s+([A-Za-z0-9_]+)\s+((?:"(?:[^"\\]|\\.|)*"\s*)+)',
            header_text):
        parts = re.findall(r'"((?:[^"\\]|\\.)*)"', value)
        literal = "".join(parts)
        decoded = literal.encode("ascii", "ignore").decode(
            "unicode_escape").encode("latin-1", "ignore")
        try:
            text = decoded.decode("utf-8", "replace")
        except UnicodeDecodeError:
            continue
        for ch in text:
            points.add(ord(ch))
    return points


def server_fixture_points() -> set[int]:
    """Code points actually in the companion fixture pack content."""
    sys.path.insert(0, str(ROOT / "companion/passport-server"))
    from passport_server.fixture import ITINERARY, PLACES, STOP_TEXTS, TICKET
    text = (json.dumps(ITINERARY, ensure_ascii=False)
            + json.dumps(PLACES, ensure_ascii=False)
            + json.dumps(TICKET, ensure_ascii=False)
            + "".join(STOP_TEXTS.values()))
    return {ord(ch) for ch in text}


def main() -> int:
    re_mod = __import__("re")
    globals()["re"] = re_mod
    points = extract_codepoints(TEXT_H.read_text(encoding="utf-8"))
    points |= server_fixture_points()
    negative_found = points & NEGATIVE
    if negative_found:
        print("negative control code point present in canopy: "
              f"{sorted(hex(p) for p in negative_found)}")
        return 1
    points.add(0x752A)  # PRD-required glyph test, stated explicitly
    threshold = 0x7F
    subset = sorted(cp for cp in points if cp > threshold)
    inventory = {
        "ascii_range": list(range(ASCII_RANGE[0], ASCII_RANGE[1] + 1)),
        "cjk_codepoints": [f"U+{cp:04X}" for cp in subset],
        "negative_control": sorted(f"U+{cp:04X}" for cp in NEGATIVE),
        "sizes": sorted(SIZES),
        "converter": f"lv_font_conv {CONVERTER_VERSION}",
        "source_font": "Noto Sans CJK SC (OFL 1.1), see assets/fonts/README.md",
    }
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "travel_glyph_inventory.json").write_text(
        json.dumps(inventory, indent=1) + "\n", encoding="utf-8")
    # C header for device-side activation glyph checks (no LVGL dependency).
    header = ROOT / "main/passport/passport_glyph_inventory.h"
    with header.open("w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/gen_passport_fonts.py; do not edit */\n"
                 "#ifndef PASSPORT_GLYPH_INVENTORY_H\n"
                 "#define PASSPORT_GLYPH_INVENTORY_H\n"
                 "#include <stdint.h>\n"
                 "static const uint32_t TRAVEL_GLYPHS[] = {")
        fh.write(", ".join(f"0x{cp:04X}" for cp in subset))
        fh.write("};\n#define TRAVEL_GLYPH_COUNT "
                 f"{len(subset)}u\n#endif\n")

    font_source = os.environ.get("PASSPORT_FONT_SOURCE")
    if not font_source or not Path(font_source).is_file():
        print("set PASSPORT_FONT_SOURCE to a licensed CJK TTF/OTF", file=sys.stderr)
        return 1
    symbol = "".join(chr(cp) for cp in subset)
    with tempfile.NamedTemporaryFile("w", suffix=".txt", encoding="utf-8") as tf:
        tf.write(symbol)
        tf.flush()
        for size in sorted(SIZES):
            cmd = [
                LV_FONT_CONV,
                "--font", font_source,
                "-r", f"0x{ASCII_RANGE[0]:X}-0x{ASCII_RANGE[1]:X}",
                "--symbols", symbol,
                "--size", str(size), "--bpp", "4", "--no-compress",
                "--lv-font-name", f"travel_font_{size}",
                "--lv-include", "lvgl.h",
                "--format", "lvgl",
                "-o", str(OUT_DIR / f"travel_font_{size}.c"),
            ]
            print("running:", " ".join(cmd[:2]), f"... size={size}")
            subprocess.run(cmd, check=True)
    print(f"glyph inventory: {len(subset)} CJK code points; "
          "negative controls absent by construction")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
